[package]
name = "polars-features"
version = "0.1.0"
edition = "2021"

[lib]
name = "_polars_features_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["abi3-py310", "extension-module"] }
pyo3-polars = { version = "0.27", features = ["derive"] }
polars = { version = "0.54", features = ["rolling_window", "fmt", "performant", "lazy", "zip_with", "random", "ndarray"] }
faer = "0.24"
faer-ext = { version = "0.8", features = ["ndarray"] }
ndarray = "0.17"
serde = { version = "1", features = ["derive"] }
hashbrown = "0.15"
numpy = "0.28"
