"""Acceptance tests for the long-memory estimators and the data-driven frac-diff.

The headline acceptance criterion from the plan: ``d`` must be **recovered on an
ARFIMA simulation**. The simulation itself is built from the fractional
integration filter ``(1 - L)^-d``, i.e. the exact inverse of the frac-diff
kernel under test, so the target value is known by construction.

This file also carries the regression tests for the frac-diff divergence guard
(hand-computed golden weights, the ``max_width`` bound, and the rejection of the
non-summable ``d < 0`` kernel).
"""

from __future__ import annotations

import numpy as np
import polars as pl
import pytest

from polars_features._ffd import SAFETY_MAX_WIDTH, estimate_ffd_order, ffd_weights
from polars_features.core import PanelFrame
from polars_features.econ.features import (
    AutoFracDiff,
    estimate_fractional_order,
    gph,
    local_whittle,
    long_memory_table,
    rolling_long_memory_features,
)


def arfima_noise(
    d: float, n: int, *, seed: int = 0, truncation: int = 4000
) -> np.ndarray:
    """Simulate ``(1 - L)^-d eps``: fractionally-integrated white noise.

    The integration weights are the binomial coefficients of ``(1 - L)^-d``,
    ``psi_k = Gamma(k + d) / (Gamma(d) Gamma(k + 1))``, generated by the same
    recursion the differencing filter uses with ``-d``. Long-memory series need a
    long truncation, hence the 4000-term default.
    """
    rng = np.random.default_rng(seed)
    eps = rng.standard_normal(n + truncation)
    psi = np.empty(truncation)
    psi[0] = 1.0
    for k in range(1, truncation):
        psi[k] = psi[k - 1] * (k - 1 + d) / k
    return np.convolve(eps, psi)[truncation : truncation + n]


# --------------------------------------------------------------------------- #
# d recovery
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("d_true", [0.0, 0.2, 0.35])
def test_local_whittle_recovers_d_on_arfima(d_true: float) -> None:
    estimates = [
        local_whittle(arfima_noise(d_true, 4096, seed=s), bandwidth_exponent=0.7).d
        for s in range(8)
    ]
    assert float(np.mean(estimates)) == pytest.approx(d_true, abs=0.08)


@pytest.mark.parametrize("d_true", [0.0, 0.2, 0.35])
def test_gph_recovers_d_on_arfima(d_true: float) -> None:
    estimates = [
        gph(arfima_noise(d_true, 4096, seed=s), bandwidth_exponent=0.7).d
        for s in range(8)
    ]
    # GPH is noisier than local-Whittle, hence the looser tolerance.
    assert float(np.mean(estimates)) == pytest.approx(d_true, abs=0.12)


def test_local_whittle_is_more_precise_than_gph() -> None:
    lw = np.std([local_whittle(arfima_noise(0.3, 2048, seed=s)).d for s in range(12)])
    g = np.std([gph(arfima_noise(0.3, 2048, seed=s)).d for s in range(12)])
    assert lw < g


def test_estimate_fractional_order_handles_a_random_walk() -> None:
    rng = np.random.default_rng(4)
    rw = np.cumsum(rng.standard_normal(2048))
    res = estimate_fractional_order(rw, bandwidth_exponent=0.7)
    # A random walk is I(1); the estimator must take the difference-and-add-one
    # path rather than clipping at the stationary boundary.
    assert res.differenced is True
    assert res.d == pytest.approx(1.0, abs=0.15)


def test_long_memory_result_reports_a_significance_test() -> None:
    res = local_whittle(arfima_noise(0.4, 4096, seed=1), bandwidth_exponent=0.7)
    assert res.se > 0
    assert res.pvalue < 0.01  # d = 0.4 is decisively different from zero
    white = local_whittle(arfima_noise(0.0, 4096, seed=1), bandwidth_exponent=0.7)
    assert white.pvalue > 0.05


def test_estimators_reject_short_series() -> None:
    with pytest.raises(ValueError, match="at least 16"):
        gph(np.arange(10.0))
    with pytest.raises(ValueError, match="at least 16"):
        local_whittle(np.arange(10.0))


def test_estimate_fractional_order_rejects_unknown_method() -> None:
    with pytest.raises(ValueError, match="unknown method"):
        estimate_fractional_order(arfima_noise(0.2, 512), method="mle")


# --------------------------------------------------------------------------- #
# frac-diff divergence guard (the M2 bug fix)
# --------------------------------------------------------------------------- #
def test_ffd_weights_match_hand_computed_golden_values() -> None:
    """Golden weights from the recursion ``w_k = -w_{k-1} (d - k + 1) / k``.

    For ``d = 0.5``: ``w0 = 1``, ``w1 = -0.5``, ``w2 = -(-0.5)(0.5-1)/2 =
    -0.125``, ``w3 = -(-0.125)(0.5-2)/3 = -0.0625``, ``w4 =
    -(-0.0625)(0.5-3)/4 = -0.0390625``. Stored oldest-to-newest.
    """
    got = ffd_weights(0.5, threshold=0.03, max_width=5)
    expected = np.array([-0.0390625, -0.0625, -0.125, -0.5, 1.0])
    np.testing.assert_allclose(got, expected, atol=1e-15)

    # d = 1 is the exact first difference; d = 0 the identity.
    np.testing.assert_allclose(ffd_weights(1.0, 1e-9), np.array([-1.0, 1.0]))
    np.testing.assert_allclose(ffd_weights(0.0, 1e-9), np.array([1.0]))

    # d = 2 is the exact second difference [1, -2, 1].
    np.testing.assert_allclose(ffd_weights(2.0, 1e-9), np.array([1.0, -2.0, 1.0]))


def test_ffd_weights_respect_max_width_exactly() -> None:
    """Regression: ``max_width`` used to be checked *after* appending, so a cap
    of 1 returned two weights."""
    for cap in range(1, 8):
        assert ffd_weights(0.4, 1e-12, cap).shape[0] == cap


def test_ffd_weights_reject_the_divergent_negative_d_kernel() -> None:
    """``d < 0`` is fractional *integration*: the truncated filter diverges.

    With ``d = -0.5`` the weights decay like ``k**-0.5``; they never reach the
    default threshold, the old code silently returned a 100 000-tap kernel whose
    sum grows without bound, and every row of a normal-length series came back
    null. It must now raise instead.
    """
    with pytest.raises(ValueError, match="fractional \\*integration\\*"):
        ffd_weights(-0.5)
    with pytest.raises(ValueError, match="must be finite"):
        ffd_weights(float("nan"))


def test_ffd_weights_raise_when_the_kernel_never_decays() -> None:
    with pytest.raises(ValueError, match="safety cap"):
        ffd_weights(0.1, threshold=1e-30)
    # An explicit max_width is an informed opt-in to truncation and must not raise.
    assert ffd_weights(0.1, threshold=1e-30, max_width=50).shape[0] == 50


def test_divergent_kernel_would_have_blown_up() -> None:
    """Evidence for the guard: the ``d < 0`` kernel is genuinely non-summable.

    Reproduces the old behaviour by hand and shows the partial sums growing
    without bound as the window lengthens -- which is exactly what the truncated
    filter's output did.
    """

    def partial_sums(d: float, terms: int) -> np.ndarray:
        w = [1.0]
        for k in range(1, terms):
            w.append(-w[-1] * (d - k + 1) / k)
        return np.cumsum(np.abs(w))

    terms = SAFETY_MAX_WIDTH // 100
    diverging = partial_sums(-0.5, terms)
    converging = partial_sums(0.5, terms)
    # Ten times the window: the d < 0 kernel keeps accumulating (sum ~ sqrt(K)),
    # the d > 0 kernel has already converged.
    assert diverging[-1] > 2.5 * diverging[terms // 10]
    assert converging[-1] < 1.05 * converging[terms // 10]
    # And the d < 0 weights never get near the default 5e-4 cut-off, which is
    # why the old code ran all the way to the safety cap.
    assert abs(partial_sums(-0.5, terms)[-1] - partial_sums(-0.5, terms - 1)[-1]) > 1e-3


# --------------------------------------------------------------------------- #
# data-driven differencing
# --------------------------------------------------------------------------- #
def test_estimate_ffd_order_is_wired_and_clipped() -> None:
    d = estimate_ffd_order(arfima_noise(0.35, 4096, seed=2), bandwidth_exponent=0.7)
    assert 0.0 <= d <= 1.0
    assert d == pytest.approx(0.35, abs=0.12)
    # Clipping keeps the returned order legal for `ffd_weights`.
    rng = np.random.default_rng(9)
    anti = -np.diff(np.cumsum(rng.standard_normal(2048)))  # over-differenced
    assert estimate_ffd_order(anti) >= 0.0


def _long_memory_panel(n: int = 2048) -> pl.DataFrame:
    frames = []
    for name, d in (("slow", 0.4), ("fast", 0.05)):
        frames.append(
            pl.DataFrame(
                {
                    "entity": [name] * n,
                    "time": np.arange(n, dtype=np.int64),
                    "x": arfima_noise(d, n, seed=hash(name) % 1000),
                }
            )
        )
    return pl.concat(frames)


def test_long_memory_table_orders_entities_by_persistence() -> None:
    out = long_memory_table(
        _long_memory_panel(),
        "x",
        entity="entity",
        time="time",
        bandwidth_exponent=0.7,
    )
    rows = {r["entity"]: r for r in out.to_dicts()}
    assert rows["slow"]["d"] > rows["fast"]["d"]
    assert rows["slow"]["d_se"] > 0


def test_rolling_long_memory_features_are_trailing() -> None:
    out = rolling_long_memory_features(
        _long_memory_panel(n=600),
        "x",
        entity="entity",
        time="time",
        window=256,
    )
    col = out.get_column("x_d")
    assert col.head(255).is_null().all()
    assert col.slice(255, 50).is_not_null().all()


def test_auto_fracdiff_fits_per_entity_orders_on_train_only() -> None:
    df = _long_memory_panel()
    panel = PanelFrame(df, entity="entity", time="time")
    tr = AutoFracDiff(["x"], bandwidth_exponent=0.7).fit(panel)
    assert tr.orders_[("slow", "x")] > tr.orders_[("fast", "x")]
    out = tr.transform(panel).collect()
    assert "x_ffd" in out.columns
    assert out.get_column("x_ffd").is_not_null().sum() > 0


def test_auto_fracdiff_transform_uses_frozen_orders() -> None:
    df = _long_memory_panel()
    panel = PanelFrame(df, entity="entity", time="time")
    tr = AutoFracDiff(["x"], bandwidth_exponent=0.7).fit(panel)
    frozen = dict(tr.orders_)
    # Transforming a different (later) panel must not change the fitted orders.
    later = PanelFrame(df.filter(pl.col("time") >= 1024), entity="entity", time="time")
    tr.transform(later)
    assert tr.orders_ == frozen


def test_auto_fracdiff_rejects_negative_d_min() -> None:
    with pytest.raises(ValueError, match="diverges for"):
        AutoFracDiff(["x"], d_min=-0.5)
